//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zerohunger.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZeroHungerEntities : DbContext
    {
        public ZeroHungerEntities()
            : base("name=ZeroHungerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<collector> collectors { get; set; }
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<restrurant> restrurants { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
